"""remind date and created not null

Revision ID: 0a0b4e6db908
Revises: 417e8b744888
Create Date: 2020-05-31 14:13:39.313606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a0b4e6db908'
down_revision = '417e8b744888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('remind_date', sa.DateTime(), nullable=False))
    op.alter_column('reminder', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminder', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('reminder', 'remind_date')
    # ### end Alembic commands ###
