"""Reminder status

Revision ID: 13434c08285f
Revises: e20ea5d43b43
Create Date: 2020-06-06 09:13:25.093158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '13434c08285f'
down_revision = 'e20ea5d43b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status = postgresql.ENUM('PENDING', 'SUCCESS', 'ERROR', name='statusenum')
    status.create(op.get_bind())
    op.add_column('reminder', sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'ERROR', name='statusenum'), server_default='PENDING', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder', 'status')
    op.execute("DROP TYPE statusenum")
    # ### end Alembic commands ###
