"""Reminder request status id

Revision ID: 279ddd5550ce
Revises: 09f04b1835ef
Create Date: 2020-06-14 10:22:28.052518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279ddd5550ce'
down_revision = '09f04b1835ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('reminder_request_status_id', sa.BigInteger(), nullable=True))
    op.execute('UPDATE reminder SET reminder_request_status_id=0;')
    op.alter_column('reminder', sa.Column('reminder_request_status_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder', 'reminder_request_status_id')
    # ### end Alembic commands ###
