"""Nonono

Revision ID: ba98311c68e4
Revises: 279ddd5550ce
Create Date: 2020-06-14 10:58:27.723817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba98311c68e4'
down_revision = '279ddd5550ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminder', 'reminder_request_status_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminder', 'reminder_request_status_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
