"""empty message

Revision ID: f43fb2620154
Revises: 0a0b4e6db908
Create Date: 2020-05-31 15:19:30.671473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43fb2620154'
down_revision = '0a0b4e6db908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reminder_author_id_fkey', 'reminder', type_='foreignkey')
    op.drop_column('reminder', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reminder_author_id_fkey', 'reminder', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
