"""Change user fields

Revision ID: fd963b761d85
Revises: f43fb2620154
Create Date: 2020-05-31 15:25:48.515275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd963b761d85'
down_revision = 'f43fb2620154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('external_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('screen_name', sa.String(), nullable=False))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'active')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'screen_name')
    op.drop_column('user', 'name')
    op.drop_column('user', 'external_id')
    # ### end Alembic commands ###
